import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'

// { children = null, backgroundHeight = true, backgroundUrl = "/images/indexBG.webp" }: { children: React.ReactNode, backgroundHeight: boolean, backgroundUrl: string }

export default function Layout({ children }: { children: React.ReactNode }): JSX.Element {
    return (
        <>
            <Head>
                <title>PET Elétrica UFBA</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.svg" />
            </Head>

            <Header />

            {children}

            <Footer />
        </>
    )
}